// File used to give the animations a user-friendly name
// Please, note that these were created by the developer, so, feel free to suggest improvements
// Also, some of these animations are repeated within the game's binary data, not sure why
const COMMON = {
  idle: "idle",
  tired: "tired",
  walking: "walking",
  running: "running",
  joyful: "joyful",
  standingUp: "standing up",
};

export const ANIMATIONS = [
  COMMON.idle,
  COMMON.tired,
  COMMON.walking,
  "stumbling",
  COMMON.running,
  "happy",
  "throw",
  "finicky",
  "eating",
  "sleeping",
  "pooping",
  COMMON.joyful,
  "angry",
  "no",
  COMMON.tired,
  "hungry",
  "toilet",
  "dizzy",
  COMMON.tired,
  "contemplating",
  "pointing",
  COMMON.standingUp,
  "yes",
  "staggering",
  "looking up",
  "looking down",
  "falling",
  "pushing",
  "coming down",
  "checking",
  "relaxing",
  "leaving",
  "preparing",
  COMMON.idle,
  COMMON.tired,
  COMMON.walking,
  COMMON.running,
  "defending",
  "petting",
  "waving",
  "falling back",
  "falling forward",
  COMMON.joyful,
  "fainting",
  COMMON.standingUp,
  "attack 0",
  "attack 1",
  "attack 2",
  "attack 3",
  "attack 4",
  "attack 5",
  "attack 6",
  "attack 7",
  "attack 8",
  "attack 9",
  "attack 10",
  "attack 11",
  "attack 12",
  "attack 13",
  "attack 14",
];
